Repository googleapis/google-api-php-client, pull requests merged in 2019-06, with the labels that each got.

#1646 Delete url-shortener.php
  examples/README.md
  examples/index.php
  examples/url-shortener.php
  tests/examples/indexTest.php
  tests/examples/urlShortenerTest.php
Labels: cla: yes

#1644 Add option to toggle API format version
  .travis.yml
  src/Google/Client.php
  tests/Google/ClientTest.php
Labels: :rotating_light:, cla: yes

#1668 docs: Adds developer docs to repo: Fixes #1648 Fixes #1649 Fixes #165…
  README.md
  docs/README.md
  docs/api-keys.md
  docs/auth.md
  docs/id-token.md
  docs/install.md
  docs/media.md
  docs/oauth-server.md
  docs/oauth-web.md
  docs/pagination.md
  docs/parameters.md
  docs/start.md
Labels: cla: yes

#1670 docs: Update links in README to point to new docs living inside repo
  README.md
  docs/oauth-server.md
Labels: cla: yes, type: docs

#1673 fix docs link
  docs/api-keys.md
Labels: cla: yes
